# Generated by Django 3.0.7 on 2020-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swagat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_item',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
